name: Pack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4

    - name: setup python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.12'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: execute py script
      run: python pack.py

    - name: upload
      uses: actions/upload-artifact@v4.3.3
      with:
        name: export
        # A file, directory or wildcard pattern that describes what to upload
        path: export
